name: JSaction
on: push
jobs:
  testing-actiobn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: send a slackmessage
        uses: ./.github/actions/slack
        with:
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
          message: Hello slack
      - uses: ./.github/actions/hello-docker1
        id: hello
        with:
          who-to-greet: "MEWorld"
      - run: |
          echo "Time:${{ steps.hello.outputs.time }}"
