name: JSaction 
on:
  pull_request:
    branches:
      - develop1
      - master22
jobs:
  testing-actiobn:
    runs-on: ubuntu-latest
    steps:
      - name: using actions 
        uses: actions/checkout@v3
      - name: using simple js action 
        id: "jav"
        uses: Nagasree2000/Simple-Javascript@v1
        with:
          who-to-greet: "Yarajarla Nagasree"
      - run: 
          echo "${{ steps.jav.outputs.time }}"
