name: JSaction
on: push
jobs:
  testing-actiobn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: send a slackmessage
        uses: actions/javascript-action@v1
        with:
          milliseconds: 1000