name: JSaction
on: push
jobs:
  testing-actiobn:
    runs-on: ubuntu-latest
    steps:
      - name: using actions 
        uses: actions/checkout@v3
      - name: using simple js action 
        id: "jav"
        uses: ./.github/actions/hello
        with:
          who-to-greet: "Yarajarla Nagasree"
      - run: 
          echo "Time is :${{ steps.jav.outputs.time }}""
