name: openissue
on: push1
jobs:
  testing-actiobn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Nagasree2000/simple-open-issue@v1
        id: issue
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Issue Creation
          body: Issue was created by Yarajarla Naga Sree for testing purpose
          assignees: |
            Nagasree2000
            Nagasree1976
      - uses: Nagasree2000/Simple-Javascript@v1
        id: "hello"
        with:
          who-to-greet: "Yarajarla Nagasree"
      - run: echo "${{ steps.hello.outputs.time }}"
      - run: echo "${{ steps.issue.outputs.issue }}"
