name: openissue
on: push
jobs:
  testing-actiobn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
      - uses: ./.github/actions/issue
        id: issue
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Issue Creation
          body: Issue was created by Yarajarla Naga Sree for testing purpose
          assignees: |
            Nagasree2000
            Nagasree1976
      - run: 
          echo "${{ steps.issue.outputs.issue }}"
