name: CI
on:
  pull_request:
    branches:
      - develop
      - master
  push:
    branches:
      - develop
      - master
jobs:
  buid:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm ci
      - run: npm run format:check
      - run: npm test -- --coverage
        env:
          CI: true
      - name: upload test coverage
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage
          path: coverage
      - name: npm run build
        if: github.event_name=='push'
        run: npm run build
      - name: upload build coverage
        if: github.event_name== 'push'
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: build
      - run: npm -g install surge --save
      - name: Deploy to surge
        if: github.event_name=='push'
        run: surge --project ./build --domain yielding-measure.surge.sh
        env:
          SURGE_LOGIN: ${{secrets.SURGE_LOGIN}}
          SURGE_TOKEN: ${{secrets.SURGE_TOKEN}}
      - name: create a release
        if: github.event_name == 'push' && github.ref== 'refs/heads/master'
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Cache modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{runner.os}}-node-${{ hashfiles('**/package-lock.json')}}
          restore-keys: |
            ${{runner.os}}-node-
