name: Raising issue
author: Nagasree2000
description: Raising a simple issue
inputs:
  token:
    description: "Github Token"
    required: true
  title:
    description: "Issue title"
    required: true
  body:
    description: "issue body"
  assignees:
    description: "Issue assignees"
outputs:
  issue:
    description: "The issue object as a json string"
runs:
  using: "node12"
  main: "gist/index.js"
